version: "3.8"
services:
  mysql:
    image: 'mariadb:latest'
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=chatbotmoodle_bd
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
  web:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
