services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot_web
    ports:
      - "8080:80"
    volumes:
      - ./volumes/html:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: chatbot_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatbot_moodle
    ports:
    
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/chatbot_moodle.sql:/docker-entrypoint-initdb.d/chatbot_moodle.sql

volumes:
  db_data: